# Generated by Django 4.2.7 on 2024-04-24 03:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0007_alter_comment_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='BlogComment',
        ),
    ]
