# Generated by Django 4.2.7 on 2024-05-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_event_gallery_alter_blog_user_alter_blogcomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Đã kiểm duyệt'),
        ),
    ]
