# Generated by Django 4.2.7 on 2024-04-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='Phương thức')),
                ('endpoint', models.CharField(max_length=2000, verbose_name='Đường dẫn')),
                ('status_code', models.IntegerField(verbose_name='Mã HTTP')),
                ('state_message', models.CharField(choices=[('PROCESS', 'Đang xử lý'), ('PENDDING', 'Chờ đợi'), ('SUCCESS', 'Thành công'), ('ERROR', 'Thất bại')], default='PROCESS', max_length=50, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời giann')),
                ('scheme', models.CharField(max_length=8, verbose_name='SSL')),
                ('domain', models.CharField(max_length=255, verbose_name='Miền')),
                ('ip', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('machinename', models.CharField(max_length=255, verbose_name='Tên máy')),
                ('machineinfo', models.CharField(max_length=255, verbose_name='Thông tin thiết bị')),
            ],
        ),
    ]
