# Generated by Django 4.2.7 on 2024-04-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='endpoint',
            field=models.TextField(verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='log',
            name='state_message',
            field=models.CharField(max_length=100, verbose_name='Đường dẫn'),
        ),
    ]
