# Generated by Django 4.2.7 on 2024-04-20 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_blog_description_comment_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_to_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_blog.comment'),
        ),
    ]
